# Generated by Django 5.0.3 on 2024-03-28 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
