# Generated by Django 5.0.3 on 2024-03-31 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_birth_date_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taste',
            new_name='Like',
        ),
        migrations.RenameModel(
            old_name='User_Taste',
            new_name='User_like',
        ),
        migrations.RenameField(
            model_name='user_like',
            old_name='taste_id',
            new_name='like_id',
        ),
    ]
