# Generated by Django 5.0.3 on 2024-04-21 05:20

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_taste_like_rename_user_taste_user_like_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='friend',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
