# Generated by Django 5.0.3 on 2024-03-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amigo_nombre_apellido', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('aceptada', 'Aceptó solicitud'), ('rechazada', 'Rechazó solicitud')], max_length=20)),
                ('foto_amigo', models.ImageField(blank=True, null=True, upload_to='fotos_amigos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('hora_creacion', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
