# Generated by Django 5.0.3 on 2024-03-28 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_user_image_client_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_evento', models.IntegerField(primary_key=True, serialize=False)),
                ('ami_id_usuario', models.IntegerField(null=True)),
                ('id_usuario', models.IntegerField(null=True)),
                ('fecha_cita', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('tipo_evento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OutFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vestimenta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion', models.FloatField()),
                ('ubicacion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.friend')),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.event')),
            ],
        ),
        migrations.CreateModel(
            name='OutFit_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.event')),
                ('id_outFit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.outfit')),
            ],
        ),
    ]
