# Generated by Django 5.0.3 on 2024-03-28 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ami_id_usuario',
        ),
        migrations.RemoveField(
            model_name='event',
            name='fecha_cita',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id_usuario',
        ),
    ]
