# Generated by Django 5.0.3 on 2024-03-30 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='duration',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
