# Generated by Django 5.0.3 on 2024-03-28 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_remove_event_ami_id_usuario_remove_event_fecha_cita_and_more'),
        ('users', '0003_user_image_client_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='id_evento',
            new_name='id_event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='tipo_evento',
            new_name='type_event',
        ),
        migrations.RenameField(
            model_name='outfit',
            old_name='tipo_vestimenta',
            new_name='type_outfit',
        ),
        migrations.RenameField(
            model_name='outfit_event',
            old_name='id_evento',
            new_name='id_event',
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.FloatField()),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.event')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.friend')),
            ],
        ),
        migrations.DeleteModel(
            name='Alquiler',
        ),
    ]
