# Generated by Django 5.0.3 on 2024-03-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_rename_id_evento_event_id_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            name='client',
            model_name='rent',
        ),
        migrations.RemoveField(
            name='friend',
            model_name='rent',
        ),
    ]
