# Generated by Django 5.0.3 on 2024-03-28 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_remove_rent_client_remove_rent_friend'),
        ('users', '0007_remove_client_id_remove_friend_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.friend'),
            preserve_default=False,
        ),
    ]
