# Generated by Django 5.0.3 on 2024-03-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_rename_client_rent_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id_event',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
