# Generated by Django 5.0.3 on 2024-03-31 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_rent_duration'),
        ('rent', '0007_alter_event_id_event'),
    ]

    operations = [
    ]
