# Generated by Django 5.0.3 on 2024-03-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_merge_20240330_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='friend_id',
            new_name='friend',
        ),
        migrations.AddField(
            model_name='rent',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=1998),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='id_event',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
