# Generated by Django 5.0.3 on 2024-03-31 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_merge_20240330_2028'),
        ('rent', '0009_rename_client_id_rent_client_and_more'),
    ]

    operations = [
    ]
