# Generated by Django 5.0.3 on 2024-03-31 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_merge_20240331_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='outfit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rent.outfit_event'),
            preserve_default=False,
        ),
    ]
