# Generated by Django 5.0.3 on 2024-03-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_rent_outfit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='id',
        ),
        migrations.AddField(
            model_name='outfit',
            name='id_oufit',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
