# Generated by Django 5.0.3 on 2024-03-31 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0012_remove_outfit_id_outfit_id_oufit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='outfit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.outfit'),
        ),
        migrations.DeleteModel(
            name='OutFit_Event',
        ),
    ]
