# Generated by Django 4.1.7 on 2024-04-23 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0013_alter_rent_outfit_delete_outfit_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.event'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='outfit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.outfit'),
        ),
    ]
