# Generated by Django 4.1.7 on 2024-04-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0014_alter_rent_description_alter_rent_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
