# Generated by Django 5.0.3 on 2024-05-19 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0016_clientcoment'),
        ('users', '0025_alter_user_personal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcoment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
    ]
