# Generated by Django 4.1.7 on 2024-04-19 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_rename_taste_like_rename_user_taste_user_like_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=50)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.friend')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
